# Configuration file for Travis CI.

language: python
python:
  - "2.7"

before_script:
  - echo DEBUG = False > ./mywebsite/settings_local.py

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# Run tests
script:
  coverage run --source=mywebsite --omit=*/migrations/* manage.py test
