# Configuration file for Travis CI.

language: python
python:
  - "2.7"

before_script:
  - echo "supersecretkey" > ./local/secret_key

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# Run tests
script:
  coverage run --source=myblogapp,mywebsite --omit=*/tests.py,*/migrations/*,*/wsgi.py manage.py test

after_success: coveralls
